### ISSUE TITLE
installation issues

### ISSUE THREAD

**Issue by sharad1126** [ndelphit/apkurlgrep#4]
Hi, I was trying to install and use the `apkurlgrep`. I already have apktool installed and running in my system without any issues. But looks like `apkurlgrep` doesn't executes for me:
```
% go get -u github.com/ndelphit/apkurlgrep
% apkurlgrep -a Downloads/abc.apk 
zsh: command not found: apkurlgrep
```

**Comment by ndelphit** [comment]
Hi! It looks like you have to GO `PATH` related issue. You should add `go/bin` directory into your `PATH` in ~/.zshrc` config.
